# Site settings
title: Buzás Barnabás – Portfólió
email: buzasbarnabas04@gmail.com
url: https://barnabas47.github.io
description: "Buzás Barnabás vagyok, programtervező informatikus hallgató a Pannon Egyetemen. Ezen az oldalon megtalálod a szakmai tapasztalataimat, technológiai ismereteimet és korábbi projektjeimet."
keywords: "Buzás Barnabás, portfólió, programtervező informatikus, C#, Java, Flutter, webfejlesztés, mobilalkalmazás, GitHub"
skills: "Programozás – Mobilfejlesztés – Adatbázis-kezelés"
meta_author: Buzás Barnabás

# Google webmaster tools
google_verify:

# Bing site verification
bing_verify:

# Contact form
contact: static

# Disqus (opcionálisan üresen hagyható)
disqus_shortname:

# Color settings
color:
  primary: 18bc9c
  primary-rgb: "24,188,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Buzás Barnabás
  location: Herend, Magyarország
  social: Kapcsolat

# Social networks
social:
  - title: github
    url: https://github.com/barnabas47

# Postal address (szabadon módosítható)
address:
  - line: Herend, Veszprém
  - line: Telefon: +36202326414
  - line: Email: buzasbarnabas04@gmail.com
  - line: Születési dátum: 2004

# Credits content
credits: 'Az oldal a <a href="https://startbootstrap.com/theme/freelancer">Start Bootstrap Freelancer</a> sablonjára épül, és a Jekyll rendszerrel készült.'

# Build settings
markdown: kramdown
permalink: pretty

# Blogbejegyzések vagy projektek alapértelmezése
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
