# Site settings
title: Buzás Barnabás
email: buzasbarnabas04@gmail.com
url: https://github.com/barnabas47/barnabas47.github.io
description: "Buzás Barnabás vagyok, programtervező informatikus. Ezen az oldalon megtalálod a szakmai tapasztalataimat, technológiai ismereteimet és szoftverfejlesztési projektjeimet."
keywords: "Buzás Barnabás, portfólió, programtervező informatikus, C#, Java, Flutter, webfejlesztés, mobilalkalmazás, GitHub"
skills: "Programozás – Mobilfejlesztés – Adatbázis-kezelés"
meta_author: Buzás Barnabás

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
contact: static

# Disqus shortname
disqus_shortname: myshortname

# Color settings
color:
  primary: 4fa3ff
  primary-rgb: "79,163,255"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Buzás Barnabás
  location: Elérhetőség
  social: Kapcsolat
  credits: Kredit
  credits_author: jeromelachaud

# Social networks
social:
  - title: github
    url: https://github.com/barnabas47?tab=repositories
  - title: linkedin
    url: https://www.linkedin.com/in/barnabás-buzás-52324235a/

# Postal address
address:
  - line: "Budapest, XI. kerület"
  - line: "Herend, Veszprém megye"
  - line: "Telefon: +36202326414"
  - line: "Email: buzasbarnabas04@gmail.com"

# Build settings
markdown: kramdown
permalink: pretty
future: true

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""