# Site settings
title: Buzás Barnabás
email: buzasbarnabas04@gmail.com
url: https://barnabas47.github.io
description: "Buzás Barnabás vagyok, programtervező informatikus hallgató. Itt találhatók az eddigi projektjeim és szakmai portfólióm."
keywords: "Buzás Barnabás, programozás, webfejlesztés, szoftverfejlesztés, C#, ASP.NET, portfólió"
skills: "Programtervező informatikus - Webfejlesztő - Backend fejlesztés"
meta_author: Buzás Barnabás

# Google webmaster tools
google_verify:

# Bing site verification
bing_verify:

# Contact form
contact: static

# If you use disqus you need disqus shortname
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c
  primary-rgb: "24,188,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Buzás Barnabás
  location: Magyarország
  social: Elérhetőségek
  credits: Köszönet

# Social networks usernames
social:
  - title: github
    url: https://github.com/barnabas47
  - title: linkedin
    url: https://www.linkedin.com/in/barnabas-buzas
  - title: facebook
    url: https://www.facebook.com/barnabas.buzas

# Postal address (add as many lines as necessary)
address:
  - line: Pannon Egyetem
  - line: Veszprém, Magyarország

# Credits content
credits: 'Ez az oldal a <a href="http://startbootstrap.com">Start Bootstrap</a> Freelancer sablonjára épül, és a Jekyll rendszerrel készült.'

# Build settings
markdown: kramdown
permalink: pretty

# For posts (projektek)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
